name: Static Analysis
on:
  push:
    branches:
      - *
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.4'
      - name: Install dependencies
        run: |
          go version
          go get
      - name: Run build
        run: go build
      - name: Run linter
        run: |
          go fmt
      - name: Run testing
        run: cd test && go test -v
