name: Static Analysis
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.15.4'
      - name: Install dependencies
        run: |
          go version
          cd ./cmd/gpm
          go get
      - name: Run build
        run: |
          cd ./cmd/gpm
          go build
      - name: Run testing
        run: |
          cd ./test
          go test -v
